%% test_1
%% Тест Ванга "Документы/MCML Wang Jaques.pdf" стр. 57
MonteCarlo_Rect(...
       'is_fluor',false,'map_filename','map.mat',...
       'is_calculate_absorption_map',false,...
       'is_show_absorption_map',false,...
       'is_calculate_irradiance', false,...
       'is_show_irradiance',false,...
       'is_calculate_histograms',false,'d_hist',0.5,'d_r_hist',0.5, ...
       'with_air',true,...
       ...
       'result_filename','MC_Wang_test1',...
       ...
       'total_photons',5e5,...
       'ma',[0 1], 'ms',[0 9], 'g',[0 0.75],'n_in',[1 1],'n_out',[1 1],...
       ...
       'z',[0 1 1.2],'x',20,'y',20,...
       ...
       'dx',0.2,'dy',0.2,'dz',0.2,...
       ...
       'is_circle',true,'source_center', [5 5 0],'source_width',5,'source_direction',[0 0 1],...
       ...
       'with_PS',false,'wavelenght',405,'alpha',0.6,'PSconc_total',1,...
       'z_pentr',4,'var_conc',1,...
       ...
       'is_calculate_directed_escape',true,'is_complex_detector',false,...
       'directed_escape_radius',5,'directed_escape_refracted_angle',pi/180,...
       'is_calculate_TR',true,'T_radius', 10,'R_radius',10,...
       ...
       'is_het',false,'het_cilind', false,'x0',5, 'a', 1,'y0', 5, 'b',1, 'z0',1,'c',1,'d',1,...
       'ma_het',0.2,'ms_het',1,'g_het',0.9,...
       ...
       'min_weight', 1e-5)

load('MC_Wang_test1.mat');

R_Wang_mean = 0.09734;
R_Wang_std = 0.001;

T_Wang_mean = 0.66096;
T_Wang_std = 0.001;
 
assert(abs(R - R_Wang_mean)< R_Wang_std); 
assert(abs(T - T_Wang_mean)< T_Wang_std);

%%  test_2
%% Simple test
MonteCarlo_Rect('with_air', true,'is_calculate_TR',true,'is_calculate_irradiance', false, 'is_show_irradiance',false,'is_calculate_histograms',false,'result_filename','MC_simple_test.mat','ma',[0 0], 'ms',[0 0], 'g',[0 1], 'z',[0 1 2],'dx',0.05,'dy',0.05,'dz',0.05,'n_in',[1 1],'T_radius', 10,'R_radius',10, 'min_weight', 1e-5,'total_photons',1e6,'x',20,'y',20,'is_circle',true,'source_center', [10 10 0],'source_width',10)
load('MC_simple_test.mat');
assert(abs(R) < 0.00001); 
assert(abs(T) > 0.99999);

%% test_3
%% Тест Ванга "Документы/MCML Wang Jaques.pdf" стр. 57
MonteCarlo_Rect(...
       'is_fluor',false,'map_filename','map.mat',...
       'is_calculate_absorption_map',false,...
       'is_show_absorption_map',false,...
       'is_calculate_irradiance', false,...
       'is_show_irradiance',false,...
       'is_calculate_histograms',false,'d_hist',0.5,'d_r_hist',0.5, ...
       'with_air',true,...
       ...
       'result_filename','MC_Wang_test2',...
       ...
       'total_photons',1e6,...
       'ma',[0 1], 'ms',[0 9], 'g',[0 0],'n_in',[1 1.5],'n_out',[1 1],...
       ...
       'z',[0 1 20],'x',10,'y',10,...
       ...
       'dx',0.5,'dy',0.5,'dz',0.5,...
       ...
       'is_circle',true,'source_center', [5 5 0],'source_width',5,'source_direction',[0 0 1],...
       ...
       'with_PS',false,'wavelenght',405,'alpha',0.6,'PSconc_total',1,...
       'z_pentr',4,'var_conc',1,...
       ...
       'is_calculate_directed_escape',true,'is_complex_detector',false,...
       'directed_escape_radius',5,'directed_escape_refracted_angle',pi/180,...
       'is_calculate_TR',true,'T_radius', 10,'R_radius',10,...
       ...
       'is_het',false,'het_cilind', false,'x0',5, 'a', 1,'y0', 5, 'b',1, 'z0',1,'c',1,'d',1,...
       'ma_het',0.2,'ms_het',1,'g_het',0.9,...
       ...
       'min_weight', 1e-5)
load('MC_Wang_test2.mat');

R_Wang_mean = 0.25907;
R_Wang_std = 0.00170;

 
assert(abs(R - R_Wang_mean)< R_Wang_std); 

%% Delete files
delete 'MC_Wang_test2.mat'
delete 'MC_Wang_test1.mat'
delete 'MC_simple_test.mat'